CREATE DATABASE IF NOT EXISTS companydb;

USE companydb;

CREATE TABLE employee (
   id INT(11) NOT NULL AUTO_INCREMENT,
   name VARCHAR(45) DEFAULT NULL,
   salary INT(5) DEFAULT NULL,
   PRIMARY KEY(id)
);

DESCRIBE employee;

INSERT INTO employee VALUES 
(1, 'JOHN', 1000 ),
(2, 'PETER', 2000),
(3, 'MARY', 3000),
(4, 'JONE', 4000);


